// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/weplanx/schedule/api"
	"github.com/weplanx/schedule/bootstrap"
	"github.com/weplanx/schedule/common"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func App(value *common.Values) (*grpc.Server, error) {
	logger, err := bootstrap.UseZap()
	if err != nil {
		return nil, err
	}
	client, err := bootstrap.UseMongoDB(value)
	if err != nil {
		return nil, err
	}
	database := bootstrap.UseDatabase(client, value)
	inject := &common.Inject{
		Values: value,
		Log:    logger,
		Mongo:  client,
		Db:     database,
	}
	server, err := api.New(inject)
	if err != nil {
		return nil, err
	}
	return server, nil
}
